# Generated by Django 3.2.3 on 2021-10-19 18:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='relations',
            field=models.ManyToManyField(related_name='_user_userprofile_relations_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
