# Generated by Django 3.2.3 on 2021-10-19 19:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211019_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='relations',
            field=models.ManyToManyField(related_name='_user_userprofile_relations_+', through='user.Relation', to=settings.AUTH_USER_MODEL),
        ),
    ]
