# Generated by Django 3.2.3 on 2021-10-19 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_userprofile_x'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='x',
        ),
    ]
